### ISSUE TITLE
Missing SDS Sheets

### ISSUE THREAD

**Issue by MustardLighthouse** [khoivan88/find_sds#28]
Hello,

When I run the program on a list of 378 CAS numbers the program reports download of 354 and cannot find 15. However when I compare the downloads to my original CAS list, I identify 24 missing. 

Here is the list without 3 non-typical numbers that the program skipped.

10257-55-3
106-93-4
110489-05-9
111-87-5
124-73-2
1323-83-7
139-02-6
15022-08-9
18586-22-6
1859-08-1
2156-97-0
3687-18-1
39389-20-3
558-20-3
63316-43-8
68441-33-8
70900-21-9
7440-06-4
75-47-8
75-69-4
853-68-9

**Comment by khoivan88** [comment]
Hi,

Thank you for letting me know about this. My current thought on this issue is that there might be a duplicate in the CAS list (my count command only count unique CAS numbers)? I could investigate a little further if you don't mind sharing your 378 CAS numbers?

**Comment by sambailey54** [comment]
No Problem. I've pre-sorted the CAS list using the "UNIQUE" function in excel to remove the duplicates. The list that I provided above are the ones that will not download. Unfortunately I cannot provide the full list. I fed that specific list of 24 to the python program with the other 354 removed and it does not download anything. Maybe they aren't in the databases?

I am also receiving some errors. Removed personal info below.

 File find_sds.py", line 84, in find_sds
    with Pool(pool_size) as p:
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by khoivan88** [comment]
Yeah, very likely that those CAS numbers couldn't be found in any of the databases that I included. I'm, however, more concerned of the counting mismatch!

**Comment by sambailey54** [comment]
Yep, I'm not sure. Once I get my full CAS list I will try it again!

Thanks.

**Comment by MustardLighthouse** [comment]
I tried the list of 24 again and this is what it returned.

Still missing SDS:
{'', '853-68-9', '75-69-4', '68441-33-8', '110489-05-9', '558-20-3', '63316-43-8', 'ï»¿10257-55-3', '1859-08-1', '124-73-2', '1323-83-7', '15022-08-9'}

Summary:
        12 SDS files are missing.
        2 SDS files downloaded.

**Comment by MustardLighthouse** [comment]
A useful feature would be an argument that would add the Chemical Name to the PDF file name. In my case I have a list of CAS numbers and corresponding chemical name.

**Comment by khoivan88** [comment]
> I tried the list of 24 again and this is what it returned.
> 
> Still missing SDS:
> {'', '853-68-9', '75-69-4', '68441-33-8', '110489-05-9', '558-20-3', '63316-43-8', 'ï»¿10257-55-3', '1859-08-1', '124-73-2', '1323-83-7', '15022-08-9'}
> 
> Summary:
> 12 SDS files are missing.
> 2 SDS files downloaded.

It seems that there might be issue with some input? based on the extra quotation marks and the weird character that my program returns??

For the adding chemical name to the file name, while that might help for human readability, it could prevent this program from being useful because different OS handle white space as well as commas, dash character differently. That is why I opted for just using the CAS number for easy identification

**Comment by khoivan88** [comment]
Hi @MustardLighthouse ,

I finally got some times and look at the issue. TCI as well as ChemicalSafety website have changed their codes a little bit. I updated my code and run with the list of 21 CAS numbers you provided above:

```python
    cas_list = [
        '10257-55-3',
        '106-93-4',
        '110489-05-9',
        '111-87-5',
        '124-73-2',
        '1323-83-7',
        '139-02-6',
        '15022-08-9',
        '18586-22-6',
        '1859-08-1',
        '2156-97-0',
        '3687-18-1',
        '39389-20-3',
        '558-20-3',
        '63316-43-8',
        '68441-33-8',
        '70900-21-9',
        '7440-06-4',
        '75-47-8',
        '75-69-4',
        '853-68-9',
    ]
```

Here is the result I get:
```shell
...
Still missing SDS:
{'110489-05-9', '10257-55-3'}

Summary: 
        2 SDS files are missing.
        19 SDS files downloaded.
...
```

So yeah, just 2 files missing now. 19 out of 21 are found now :)

You do have to re-download (clone/git pull) to get my newest version.

Please let me know if you have any more questions.

Khoi

**Comment by MustardLighthouse** [comment]
Awesome! thanks for taking a look. This is a lifesaver for me.

**Comment by khoivan88** [comment]
I'm really happy to hear that my code helps 😄
