### ISSUE TITLE
find_sds, installation issue

### ISSUE THREAD

**Issue by nbehrnd** [khoivan88/find_sds#39]
Using `find_sds` within a virtual environment by Python 3.9.7 (default as provided by Linux Debian 12/bookworm, branch testing) I notice the installation *halts* when aiming to resolve the dependencies at the explicit version requirement for `idna==3.1`:

![idna](https://user-images.githubusercontent.com/19709084/132738050-091df3a2-182d-4cb9-bc35-c76f80533f4e.png)

The installation however proceeds well (including provision of a functional application) if the third line of `requirements` only reads `idna`.  In the venv created, `help(idna)` indicates that version 2.10 is loaded (based on `idna-2.10-py2.py3-none-any.whl`).

The observation is based on fetching a pristine clone of the repository (6cf1565 by May 9, 2021).

**Comment by khoivan88** [comment]
hi @nbehrnd , thank you very much for checking this on Python 3.9. I have updated the `requirements.txt`, I hope it will not have much issue now :). Again, thank you very much for this issue!
