### ISSUE TITLE
Very useful repository

### ISSUE THREAD

**Issue by sitanshubhunia** [khoivan88/find_sds#83]
Hi @khoivan88 , First of all thanks for your valuable work. Really helps me lot. Hope in near future you can add more source 🙏. 

Regards,
Sitanshu.

**Comment by khoivan88** [comment]
Thank you very much, Sitanshu. That means a great deals to know that you have found my tools useful. I am a bit busy in the mean time but definitely let me know if you have any suggestions in mind!

**Comment by sitanshubhunia** [comment]
@khoivan88 Definitely I will. When you will be free, requesting to add more look up database (s). Again thanks for valuable work.
